/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author utsma
 */
public class OperasiDuaAngkaGUI extends javax.swing.JFrame {

    /** Creates new form OperasiDuaAngkaGUI */
    public OperasiDuaAngkaGUI() {
        initComponents();
    }
    
    private void filterKeyTyped(java.awt.event.KeyEvent evt){
       char c = evt.getKeyChar();
       if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          JOptionPane.showMessageDialog(null, "Masukkan hanya angka (0 - 9) !");
          evt.consume();
       }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        angkaPertamaTF = new javax.swing.JTextField();
        angkaKeduaTF = new javax.swing.JTextField();
        hasilTF = new javax.swing.JTextField();
        operatorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tambahBtn = new javax.swing.JButton();
        kurangBtn = new javax.swing.JButton();
        kaliBtn = new javax.swing.JButton();
        bagiBtn = new javax.swing.JButton();
        keluarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Utsman", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        angkaPertamaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angkaPertamaTFKeyTyped(evt);
            }
        });

        angkaKeduaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angkaKeduaTFKeyTyped(evt);
            }
        });

        jLabel2.setText("=");

        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        kurangBtn.setText("Kurang");
        kurangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangBtnActionPerformed(evt);
            }
        });

        kaliBtn.setText("Kali");
        kaliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliBtnActionPerformed(evt);
            }
        });

        bagiBtn.setText("Bagi");
        bagiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiBtnActionPerformed(evt);
            }
        });

        keluarBtn.setText("Keluar");
        keluarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(angkaPertamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(operatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(angkaKeduaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(hasilTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kurangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kaliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bagiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angkaPertamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorLabel)
                    .addComponent(angkaKeduaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(hasilTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn)
                    .addComponent(kurangBtn)
                    .addComponent(kaliBtn)
                    .addComponent(keluarBtn)
                    .addComponent(bagiBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
        if(angkaPertamaTF.getText().equals("")||angkaKeduaTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong !", "Warning", JOptionPane.WARNING_MESSAGE); 
        } else {
             operatorLabel.setText("+");
        
             double angkaPertama = Double.parseDouble(angkaPertamaTF.getText());
             double angkaKedua = Double.parseDouble(angkaKeduaTF.getText());
        
             double hasil = angkaPertama + angkaKedua;
        
             hasilTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void angkaPertamaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkaPertamaTFKeyTyped
        // TODO add your handling code here:
       filterKeyTyped(evt);
    }//GEN-LAST:event_angkaPertamaTFKeyTyped

    private void angkaKeduaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkaKeduaTFKeyTyped
        // TODO add your handling code here:
      filterKeyTyped(evt);
    }//GEN-LAST:event_angkaKeduaTFKeyTyped

    private void kurangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangBtnActionPerformed
        // TODO add your handling code here:
        if(angkaPertamaTF.getText().equals("")||angkaKeduaTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong !", "Warning", JOptionPane.WARNING_MESSAGE); 
        } else {
             operatorLabel.setText("-");
        
             double angkaPertama = Double.parseDouble(angkaPertamaTF.getText());
             double angkaKedua = Double.parseDouble(angkaKeduaTF.getText());
        
             double hasil = angkaPertama - angkaKedua;
        
             hasilTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_kurangBtnActionPerformed

    private void kaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliBtnActionPerformed
        // TODO add your handling code here:
        if(angkaPertamaTF.getText().equals("")||angkaKeduaTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong !", "Warning", JOptionPane.WARNING_MESSAGE); 
        } else {
             operatorLabel.setText("X");
        
             double angkaPertama = Double.parseDouble(angkaPertamaTF.getText());
             double angkaKedua = Double.parseDouble(angkaKeduaTF.getText());
        
             double hasil = angkaPertama * angkaKedua;
        
             hasilTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_kaliBtnActionPerformed

    private void bagiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiBtnActionPerformed
        // TODO add your handling code here:
        if(angkaPertamaTF.getText().equals("")||angkaKeduaTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong !", "Warning", JOptionPane.WARNING_MESSAGE); 
        } else {
             operatorLabel.setText(":");
        
             double angkaPertama = Double.parseDouble(angkaPertamaTF.getText());
             double angkaKedua = Double.parseDouble(angkaKeduaTF.getText());
        
             double hasil = angkaPertama / angkaKedua;
        
             hasilTF.setText(Double.toString(hasil));
        }
    }//GEN-LAST:event_bagiBtnActionPerformed

    private void keluarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarBtnActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar aplikasi?", "Warning", JOptionPane.YES_NO_OPTION)
             ==JOptionPane.YES_OPTION){
           System.exit(0);
        }
    }//GEN-LAST:event_keluarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperasiDuaAngkaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angkaKeduaTF;
    private javax.swing.JTextField angkaPertamaTF;
    private javax.swing.JButton bagiBtn;
    private javax.swing.JTextField hasilTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kaliBtn;
    private javax.swing.JButton keluarBtn;
    private javax.swing.JButton kurangBtn;
    private javax.swing.JLabel operatorLabel;
    private javax.swing.JButton tambahBtn;
    // End of variables declaration//GEN-END:variables

}
